name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: cacao-zcap

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout cacao-zcap
      uses: actions/checkout@v2
      with:
        path: cacao-zcap

    - name: Checkout cacao-rs
      uses: actions/checkout@v2
      with:
        repository: spruceid/cacao-rs
        token: ${{ secrets.SPRUCE_CEL_PRIVATE_REPOS_2022 }}
        path: cacao-rs
        ref: 61b02a7b0eb0b4b75c04553cbf4f045066d4f1ad

    - name: Checkout ssi
      uses: actions/checkout@v2
      with:
        repository: spruceid/ssi
        ref: ea4d9cfe92bd063c259550d483d7ed4d30009441
        path: ssi

    - name: Cache Cargo registry and build artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          cacao-zcap/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('cacao-zcap/Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Test
      run: cargo check

    - name: Clippy
      run: cargo clippy
